import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "C² Racing Team",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-gray-900 relative`}>
        <div className="fixed inset-0 -z-10 w-full h-full overflow-hidden">
          <iframe
            src="https://my.spline.design/fullelectric-ZvlxRxT4AbuRLxROkgzL9Mds/"
            title="3D Car Model Overlay"
            frameBorder="0"
            width="100%"
            height="100%"
            style={{width: "100vw", height: "100vh", opacity: 1, pointerEvents: "auto"}}
            allowFullScreen
          />
        </div>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
